### ISSUE TITLE
CIs for repeated measures

### ISSUE THREAD

**Issue by ro66** [dstanley4/apaTables#15]
Hi
Thanks a lot for your really helpful package!
Is there a way to include the confidence intervals also in the ezanova.table version? Or to read the outcome from the aov() wrapper?

**Comment by dstanley4** [comment]
apaTables relies on ezANOVA from the ez package for repeated measures information. Since CI's are not part of the output from the ezANOVA command they are not included in apaTables. For independent designs, it's easy to do quick add on calculation (which I do) but not so for repeated measures designs.
