### ISSUE TITLE
apa.reg.table not printing interactions in table

### ISSUE THREAD

**Issue by lcampb23** [dstanley4/apaTables#8]
Hi there. I have a lm object (linear regression with main effects and interactions), and when using apa.reg.table it does not print the interaction terms/values in the table. This happens if I use do something like the following: m1 <- lm(dv ~ iv1 + iv2 * iv3 *iv4), or even: m2 <- lm(dv ~ iv1 + iv2 + iv3 +iv4 + iv2*iv3 +iv2*iv4 + iv3*iv4 + iv2*iv3*iv4. Do you have any suggestions? Thanks.

**Comment by dstanley4** [comment]
I think this is closed. Please let me know if you are still encounter problems and I'll reopen the issue.

**Comment by kris-ariya** [comment]
Hi I encounter this problem when using the `:` notation instead of `I()`.

For example, this block runs without any problem.

```
ibrary(apaTables)
block1 <- lm(sales ~ adverts + airplay, data = album)
block2 <- lm(sales ~ adverts + airplay + I(adverts*airplay), data = album)
apa.reg.table(block1, block2, filename = "Table3_APA.doc", table.number = 3)
```

 However,
```
 llibrary(apaTables)
 block1 <- lm(sales ~ adverts + airplay, data = album)
 block2 <- lm(sales ~ adverts + airplay +  adverts:airplay, data = album)
 apa.reg.table(block1, block2, filename = "Table3_APA.doc", table.number = 3)
```
results in
```
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```

Did I miss anything?

**Comment by dstanley4** [comment]
At this time only the I() notation is supported.


On Sep 7, 2020, at 4:24 PM, kris-ariya <notifications@github.com> wrote:

﻿

CAUTION: This email originated from outside of the University of Guelph. Do not click links or open attachments unless you recognize the sender and know the content is safe. If in doubt, forward suspicious emails to IThelp@uoguelph.ca


Hi I encounter this problem when using the : notation instead of I().

For example, this block runs without any problem.

ibrary(apaTables)
block1 <- lm(sales ~ adverts + airplay, data = album)
block2 <- lm(sales ~ adverts + airplay + I(adverts*airplay), data = album)
apa.reg.table(block1, block2, filename = "Table3_APA.doc", table.number = 3)


However,

 llibrary(apaTables)
 block1 <- lm(sales ~ adverts + airplay, data = album)
 block2 <- lm(sales ~ adverts + airplay +  adverts:airplay, data = album)
 apa.reg.table(block1, block2, filename = "Table3_APA.doc", table.number = 3)


results in

Error in rbind(deparse.level, ...) :
  numbers of columns of arguments do not match


Did I miss anything?
